zycast: disable build on non-Linux OS
Fails with following errors on MacOS builder:

[ 96%] Building C object CMakeFiles/zycast.dir/src/zycast.c.o
/usr/bin/gcc   -I/Users/runner/work/firmware-utils/firmware-utils/openwrt/tools/include -I/usr/local/opt/libressl/include -O3 -DNDEBUG -isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12.7   -Wall -Wno-unused-parameter -MD -MT CMakeFiles/zycast.dir/src/zycast.c.o -MF CMakeFiles/zycast.dir/src/zycast.c.o.d -o CMakeFiles/zycast.dir/src/zycast.c.o -c /Users/runner/work/firmware-utils/firmware-utils/src/zycast.c
/Users/runner/work/firmware-utils/firmware-utils/src/zycast.c:205:35: error: use of undeclared identifier 'MSG_MORE'
                if (send(sockfd, phdr, HDRSIZE, MSG_MORE | MSG_DONTROUTE) < 0)
                                                ^
/Users/runner/work/firmware-utils/firmware-utils/src/zycast.c:285:39: error: use of undeclared identifier 'SO_BINDTODEVICE'
                        if (setsockopt(sockfd, SOL_SOCKET, SO_BINDTODEVICE,  optarg, strlen(optarg)) < 0)
                                                           ^
2 errors generated.

These seem to be Linux only definitions and there are no equivalents,
so leave rewrite of zycast to someone interested in running it on
other OS.

Signed-off-by: Tomasz Maciej Nowak <tmn505@gmail.com>